services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    image: yerinss/client
    volumes:
      - /home/ubuntu/clientbuild:/app/apps/client/dist
    networks:
      - app_network
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    image: yerinss/server
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

networks:
  app_network:
    external: true
