name: Develop_Test
on:
  pull_request:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with: 
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
 
      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: install dependencies
        run: pnpm install
      
      - name: Create JSON file
        env:
          TYPE: ${{ secrets.TYPE }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AUTH_URI: ${{ secrets.AUTH_URI }}
          TOKEN_URI: ${{ secrets.TOKEN_URI }}
          AUTH_PROVIDER_URL: ${{ secrets.AUTH_PROVIDER_URL }}
          CLIENT_CERT_URL: ${{ secrets.CLIENT_CERT_URL }}
          UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
        run: |
          echo '{
            "type": "'"${TYPE}"'",
            "project_id": "'"${PROJECT_ID}"'",
            "private_key_id": "'"${PRIVATE_KEY_ID}"'",
            "private_key": "'"${PRIVATE_KEY}"'",
            "client_email": "'"${CLIENT_EMAIL}"'",
            "client_id": "'"${CLIENT_ID}"'",
            "auth_uri": "'"${AUTH_URI}"'",
            "token_uri": "'"${TOKEN_URI}"'",
            "auth_provider_x509_cert_url": "'"${AUTH_PROVIDER_URL}"'",
            "client_x509_cert_url": "'"${CLIENT_CERT_URL}"'",
            "universe_domain": "'"${UNIVERSE_DOMAIN}"'"
          }' > ./apps/server/service-account.json

      - name: build
        run: pnpm turbo run build

      - name: run integration tests
        run: pnpm turbo run test:integ

      - name: download playwright browsers
        run: pnpm exec playwright install
        working-directory: ./apps/client

      - name: run E2E tests
        run: pnpm turbo run test:e2e
