name: Develop_Test
on:
  pull_request:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
 
      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm turbo run build

      - name: run unit tests
        run: pnpm turbo run test

      - name: download playwright browsers
        run: pnpm exec playwright install
        working-directory: ./apps/client

      - name: run E2E tests
        run: pnpm turbo run test:e2e
