name: Deploy with Docker Compose
on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
 
      - name: Install pnpm
        run: npm install -g pnpm

      - name: install dependencies
        run: pnpm install

      - name: Generate Environment Variables File for Production
        run: echo "DATABASE_URL=$DATABASE_URL" >> .env
        working-directory: ./packages/database
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Add Environment Variables File for Production
        run: echo "SERVER_URL=$SERVER_URL" >> .env
        working-directory: ./apps/client
        env: 
          SERVER_URL: ${{ secrets.SERVER_URL }}
      
      - name: Generate Environment Variables File for Server
        run: echo "PORT=${{ secrets.PORT }}" > ./apps/server/.env
        env:
          PORT: ${{ secrets.PORT }}
        
      - name: build
        run: pnpm turbo run build

      - name: run unit tests
        run: pnpm turbo run test

      - name: run integration test
        run: pnpm turbo run test:integ

      - name: download playwright browsers
        run: pnpm exec playwright install
        working-directory: ./apps/client

      - name: run E2E test
        run: pnpm turbo run test:e2e

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        run: |
          docker compose build
          docker compose push

      - name: Pull and restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd ./kkoo
            docker compose down
            docker compose pull
            docker compose up -d
            docker image prune -f
            sudo systemctl restart nginx
