name: Deploy with Docker Compose
on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
 
      - name: Install pnpm
        run: npm install -g pnpm

      - name: install dependencies
        run: pnpm install

      - name: run unit tests
        run: pnpm turbo run test

      - name: run E2E tests
        run: pnpm turbo run test:e2e

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        run: |
          docker compose build
          docker compose push

      - name: Pull and restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            docker compose pull
            docker compose -f docker-compose.yml up -d --build
            docker image prune -f
            sudo systemctl restart nginx
